steps: steps:
   - name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: 'bash'
     args:
       - '-c'
       - |
         source ${BRANCH_NAME}.env
         echo $${_MY_VARIABLE_1}
         echo $${_MY_VARIABLE_2}
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      [
        'beta', 
        'run', 
        'deploy', 
        '$TRIGGER_NAME', 
        '--image', 
        'gcr.io/$PROJECT_ID/$TRIGGER_NAME', 
        '--region',
        'asia-east1',
        '--platform', 
        'managed', 
        '--quiet']
images:
  - gcr.io/$PROJECT_ID/$TRIGGER_NAME